### ISSUE TITLE
Naming positional arguments - best practices in R?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#112]
https://github.com/jhudsl/intro_to_R_class/issues/77

**Comment by carriewright11** [comment]
thought it might make sense for us to check each of our lectures... so I will assign each of us - accidentally did it to the closed issue first :P

**Comment by avahoffman** [comment]
- [ ] RStudio
- [ ] Reproducibility
- [ ] Basic R
- [ ] Data IO
- [ ] Subsetting
- [ ] Summarization
- [ ] Data classes
- [ ] Data cleaning
- [ ] Manipulating
- [ ] Esquisse
- [ ] Data viz
- [ ] factors
- [ ] Statistics
- [ ] Functions

**Comment by carriewright11** [comment]
I see that there are multiple files for the rstudio lab that seem to be duplicates.. .maybe from the rendering - can I delete one @avahoffman - not sure which...

**Comment by avahoffman** [comment]
Not sure where that is from. But RStudio_Lab.Rmd and html is what is linked on the website.. so that's probably what we should use

**Comment by avahoffman** [comment]
@carriewright11 I am going to mention this and explain in Data Input. I think we just have to be clear that people use non-standard evaluation sometimes

**Comment by carriewright11** [comment]
OK sure
