### ISSUE TITLE
Use `exrcise` package to automatically set up your exercises and keys

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#114]
https://github.com/jhudsl/intro_to_R_class/issues/71

**Comment by carriewright11** [comment]
I think this is done

**Comment by carriewright11** [comment]
@avahoffman this PR did this right? https://github.com/jhudsl/intro_to_r/pull/548

**Comment by avahoffman** [comment]
i used a different approach, but yes :)
