### ISSUE TITLE
put bonus questions at the _end_ of each lab chunk

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#122]

**Comment by carriewright11** [comment]
@avahoffman you mean labs right?

**Comment by carriewright11** [comment]
- [ ]  RStudio
- [ ]  Reproducibility
- [ ]  Basic R
- [ ]  Data IO
- [ ]  Subsetting
- [ ]  Summarization
- [ ]  Data classes
- [ ]  Data cleaning
- [ ]  Manipulating
- [ ]  Esquisse
- [ ]  Data viz
- [ ]  factors
- [ ]  Statistics
- [ ]  Functions

**Comment by avahoffman** [comment]
Per @carriewright11 and my discussion, bonuses should be after each lab breakout/chunk

**Comment by avahoffman** [comment]
I think this has been completed!
