### ISSUE TITLE
Glossary at the end of each lecture?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#123]
I think it would be handy to have a cheatsheet of vocab/jargon and functions at the end of each lecture as a quick reference

**Comment by avahoffman** [comment]
Maybe better to create a glossary tab on the website? I am thinking like:

`data.frame`
* a data table, similar to a spreadsheet or matrix. See `tibble`

`tibble`
* a nicely formatted `data.frame` - has a bit more formatting and is used by the tidyverse

**Comment by carriewright11** [comment]
@cansavvy  did this:
https://github.com/jhudsl/intro_to_R_class/pull/70
https://github.com/jhudsl/intro_to_R_class/pull/58
https://github.com/jhudsl/intro_to_R_class/pull/60
https://github.com/jhudsl/intro_to_R_class/pull/69

**Comment by carriewright11** [comment]
perhaps we want to combine all of these into one mega glossary though?
Also adding summaries of what we went over to each lecture could be good... or we could simply go over the cheat sheets each time?

**Comment by carriewright11** [comment]
> perhaps we want to combine all of these into one mega glossary though? Also adding summaries of what we went over to each lecture could be good... or we could simply go over the cheat sheets each time?

@avahoffman any thoughts about this?

**Comment by avahoffman** [comment]
@carriewright11 I think we have a lot of resources already.. so maybe we just link to the cheatsheet at the end of each lecture (kind of like we have the link to the course website?)
