### ISSUE TITLE
Common issues resource

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#147]
want to make this to help students fix their own code

**Comment by carriewright11** [comment]
FAQ tab on website
- forgot to reassign
- mixed and matched base and tidyverse
- forgot parentheses  (error unexpected "(")
- other common error messages - object not found - you misstyped the object name or never assigned it

**Comment by avahoffman** [comment]
"could not find function 'x'"
  - Didn't load library containing said function
  - Misspelled function

**Comment by carriewright11** [comment]
This is done https://github.com/jhudsl/intro_to_r/pull/152
