### ISSUE TITLE
Summaries at the end of lectures

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#150]
also at end of sections before labs

**Comment by avahoffman** [comment]
[ ] RStudio
[ ] Reproducibility
[ ] Basic R
[ ] Data IO
[ ] Subsetting
[ ] Summarization
[ ] Data classes
[ ] Data cleaning
[ ] Manipulating
[ ] Esquisse
[ ] Data viz
[ ] factors
[ ] Statistics
[ ] Functions

**Comment by carriewright11** [comment]
I am making summaries at the end of sections before each lab

**Comment by carriewright11** [comment]
> also at end of sections before labs

@avahoffman do we not like this practice? I thought it would be helpful for the students to perform the labs right afterwards. I will skip this for the rest of my lectures, but we can decide if we want to not do this for the future... or we could have a final summary as well that covers everything

**Comment by avahoffman** [comment]
oh okay, missed that part! Will add :)

**Comment by carriewright11** [comment]
oh ok! Only if you like the idea!

**Comment by avahoffman** [comment]
Summaries before each lab:

- [ ] Intro
- [ ] RStudio
- [ ] Reproducibility
- [ ] Basic R
- [ ] Data IO
- [ ] Subsetting
- [ ] Summarization
- [ ] Data classes
- [ ] Data cleaning
- [ ] Manipulating
- [ ] Esquisse
- [ ] Data viz
- [ ] factors
- [ ] Statistics
- [ ] Functions

**Comment by avahoffman** [comment]
Closing this in favor of #343  :)
