### ISSUE TITLE
recaps of previous day each day?

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#169]
this might be helpful to students but I also don't want to take up too much time

**Comment by avahoffman** [comment]
I like this idea. Maybe just showing the Summary slide?

**Comment by carriewright11** [comment]
yeah that should work - we could also have a link to the cheatsheet from the previous day

**Comment by carriewright11** [comment]
are we going to try to do this now @avahoffman

**Comment by carriewright11** [comment]
could use this: `📃[Cheatsheet](https://jhudatascience.org/intro_to_r/modules/cheatsheets/Day-2.pdf)`

**Comment by carriewright11** [comment]
and an example recap of day 2:
- R functions as a calculator
- Use `<-` to save (assign) values to objects
- if you don't use `<-` to reassign objects that you want to modify - they will not stay the same
- Use `c()` to **combine** vectors
- `length()`, `class()`, and `str()` tell you information about an object
- `head()` and `tail()` can also help you inspect an object
- `spec` can help you check data read into R with `readr`
- `readr`has helpful functions like `read_csv()` that can help you import data into R
- `readr` also has helpful functions like `write_rds()` to create files that can be double clicked from the file pane to load into your RStudio environment
📃[Cheatsheet](https://jhudatascience.org/intro_to_r/modules/cheatsheets/Day-2.pdf)

**Comment by carriewright11** [comment]
- [ ] RStudio
- [ ] Basic R
- [ ] Data IO
- [ ] Subsetting
- [ ] Summarization
- [ ] Data classes
- [ ] Data cleaning
- [ ] Manipulating
- [ ] Esquisse
- [ ] Data viz
- [ ] factors
- [ ] Statistics
- [ ] Functions
