### ISSUE TITLE
DATA IO: fix `view()`

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#171]
`view` is not a function, should be `View()`

Might be worth pointing this out explicitly before the last slide

**Comment by carriewright11** [comment]
sorry about that - I think that typo was me!
just fyi view() also worked for me when I tried it - it is puzzling that it is capitalized... do you know why it is?

**Comment by avahoffman** [comment]
@carriewright11 `view()` is from the `tibble` package, so they haven't loaded it yet.. probably best not to confuse them
