### ISSUE TITLE
Intro/RStudio notes

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#174]
- [x] define a chunk more
- [x]  more explicitly show where code goes and doesn't go
- [x]  add an image to the cheatsheet about R Markdown elements - added to reproducibility
- [ ]  maybe a video about R Markdown - I think showing live is maybe better

**Comment by carriewright11** [comment]
- [ ] show how chunks can change figure size output maybe?

- [ ] describe how you can install packages from drop downs
- [ ] describe how you can see data variables in environment: Click the play button on the lefthand side of the dataset under “Data” in the environment
-  [ ] maybe add: Some of you were asking about having the code show up in the console and not in your Rmd. All you have to do is select “Chunk output in Console” instead of “chunk output inline” - of course, this is totally up to you and what you prefer!

**Comment by carriewright11** [comment]
I think "describe how you can see data variables in environment: Click the play button on the lefthand side of the dataset under “Data” in the environment" should be done in a different lecture... maybe data IO? @avahoffman what do you think?

**Comment by avahoffman** [comment]
@carriewright11 sure!
