### ISSUE TITLE
rename bonus to advanced? or something else

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#179]
Not sure how to indicate that these go above what is needed

**Comment by carriewright11** [comment]
- [ ] RStudio
- [ ] Basic R
- [ ] Data IO
- [ ] Subsetting
- [ ] Summarization
- [ ] Data classes
- [ ] Data cleaning
- [ ] Manipulating
- [ ] Esquisse
- [ ] Data viz
- [ ] factors
- [ ] Statistics
- [ ] Functions

**Comment by avahoffman** [comment]
Maybe "optional practice" ?

**Comment by carriewright11** [comment]
I like it
