### ISSUE TITLE
DATA SUBSETTING: Notes

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#185]
- maybe cover the `package::function` concept earlier? in Basic R or data IO? Was kind of surprised to see it when it came up
- data_frame vs tibble…Warning message: `data_frame()` was deprecated in tibble 1.1.0. Please use `tibble()` instead.
- reminder of the help `?` and `??`
- some discussion of when you need quotation marks or not (eg with columns)
- Maybe we could think about excluding `relocate`? Maybe better to just `select` for practicality?
- maybe move the base R ways to the end of the lecture

**Comment by carriewright11** [comment]
thanks!

**Comment by carriewright11** [comment]
- [ ] add dplyr:: to glimpse or just say that it comes form dplyr
- [ ] add that rownames_to_colnames is in tibble
- [ ] change ascending to increasing
- [ ] add slide about needing quotation marks or not (and curly quotation marks!)
- [ ] move some base R to end
- [ ] describe ? and ??

**Comment by avahoffman** [comment]
ignore the `data_frame()` comment - a student asked a question about it , but I think they probably just went off script :)

**Comment by carriewright11** [comment]
oh ok :)
