### ISSUE TITLE
Data IO: Get rid of `spec()`?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#187]
I feel like this function isn't generalizeable enough, and perhaps they're better off focusing on `str()` ... Perhaps we mention spec once and leave it at that. thoughts?

`spec()` appears in the following:

./modules/Data_IO/Data_IO.Rmd
./modules/Data_IO/lab/Data_IO_Lab.Rmd
./modules/Data_IO/lab/Data_IO_Lab_Key.Rmd
./modules/HW/homework2_key.Rmd
./modules/HW/homework2.Rmd
./modules/cheatsheets/Day-2.md

**Comment by carriewright11** [comment]
hmm yeah I kinda agree
