### ISSUE TITLE
Data Summarization Notes

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#195]
### **Lecture:**
- moving the data class lecture first will help so you don't have to introduce logical data
- maybe add a slide about backticks and quotes (perhaps this should be earlier in basic R?)
- could explain however why we need backticks around the year variable names
- possibly more explanation of the `.x` and `~` notation in across
- explanation of when to use `n()` vs `count()` : n() can be used inside summarize()  (and also mutate()), while count() can be used on its own. These will give the same result:
` bike %>%`
        `group_by(type) %>%`
        `summarize(count = n())`

    `bike %>% count(type)`
- maybe add an explanation of grouping by two variables to the lecture or at least more in the lab on how to do that since there is a question on it
- possibly a bit more discussion on when to `ungroup()` (if you haven't reassigned don't need to)
### **Lab:**
- since we don't cover `ifelse` perhaps we should change that bonus to `recode` or `case_when` ...however we dont do that for another day (but I understand if you want a sneak peek...) (there is also a `dplyr` `if_else()`) Do we want to talk about `ifelse`? I kinda prefer sticking with `case_when` since it is more flexible and intuitive, but we could.
- perhaps move more questions to bonus - the students working through it on their own had trouble getting through it due to length
- could add hints about how to use `across()`

**Comment by carriewright11** [comment]
do we want to remove across from lecture and lab since we go over this during the functions module?

**Comment by avahoffman** [comment]
Good idea!
