### ISSUE TITLE
CLEANING: notes

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#200]
- lots of concerns about dropping so much data. Maybe need a disclaimer that we're not saying you should automatically do this on your data. Need to use best judgement (perhaps this is obvious? but got questions about it)
- some confusion on whether the `na` functions work on a vector (pulled column) or dataframe (tidy grammar)
- folks might have been distracted by the gif - maybe animate that onto a next slide? :)

**Comment by carriewright11** [comment]
thank you for these @avahoffman!!

**Comment by carriewright11** [comment]
- [ ] add warning emojis and color to make disclaimers more emphatic 
- [ ] bonus for lab part 1 - clarify to use the previous dataset not the list
- [ ] more clarity about piping with lab question 1 or possibly dont talk about any and is.na()?? or more clarity about how to work with it in a vector vs df and similary maybe more about str_* functions needing vectors... but people seemed to get it
- [ ] possibly add a code to show percent complete across columns
- [ ] possibly add starts_with function 
- [ ] typo start should be end for the argument of str_sub
- [ ] move gif to new slide
- [ ] maybe move one of the recoding questions to a bonus

**Comment by avahoffman** [comment]
Also @carriewright11 I noticed a lot of commented out text in the lecture. Is there a reason for this? I think it might confuse students if they are referring to it.

**Comment by carriewright11** [comment]
I can remove it- I changed quite a bit and wanted to leave it in case I felt like it didn't go better than last time- would you like me to remove it now?

**Comment by avahoffman** [comment]
not urgent, but maybe a to-do to clean things up for next time! I think it's still fine to have extra slides. We can always refer back to previous commits or releases if needed :)
