### ISSUE TITLE
add "The End" to last lab slide so people understand the lecture is finished

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#201]
On day 5 people were disappointed that we didn't get through all the material... except that we did.
How can we avoid this disappointment?

Perhaps just add the phrase "The End" to last lab slide?

What do you think @avahoffman ?

lol I just find it upsetting that the time management worked well (which is so difficult) but yet the students feel like we did that poorly

**Comment by avahoffman** [comment]
This might help! Or only including summaries at the end of each module perhaps?

**Comment by avahoffman** [comment]
- [ ]  RStudio
- [ ]  Reproducibility
- [ ]  Basic R
- [ ]  Data IO
- [ ]  Subsetting
- [ ]  Summarization
- [ ]  Data classes
- [ ]  Data cleaning
- [ ]  Manipulating
- [ ]  Esquisse
- [ ]  Data viz
- [ ]  factors
- [ ]  Statistics
- [ ]  Functions
