### ISSUE TITLE
Maybe cover the concept of tidy/long data for plotting during Esquisse lecture

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#209]
- Can cover briefly again when talking about ggplot.
- [x]  I think it would be a useful exercise to demonstrate how using wide data is "limiting" using esquisse. They can try both a wide and long dataset.

https://github.com/jhudsl/intro_to_r/blob/5e466776444f0b16e21b07d20cf42b6007977961/modules/Data_Visualization/Data_Visualization.Rmd#L106

**Comment by carriewright11** [comment]
yeah! also would be good to show this: 

`esquisse::esquisser(iris, viewer = "browser")`

To make the browser as default display mode, you can use this in your Rprofile :
`options("esquisse.display.mode" = "browser")`
