### ISSUE TITLE
DATA VIZ and FACTORS: notes

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#210]
Optional suggestions of course :)

Data Viz

- [x] Maybe mention how ggplot handles NAs (both numeric and categorical)
- [x] the font plot... that doesn't look like comic sans..
     - https://github.com/jhudsl/intro_to_r/blob/5e466776444f0b16e21b07d20cf42b6007977961/modules/Data_Visualization/Data_Visualization.Rmd#L295
- [x]  Typo here
     - https://github.com/jhudsl/intro_to_r/blob/5e466776444f0b16e21b07d20cf42b6007977961/modules/Data_Visualization/Data_Visualization.Rmd#L300
- [x] Folks still a little confused about the hint commented out during lab. Suggest we move to placing it above (in the markdown)
-  [x] #295 -  gonna backlog this for now 
     - https://github.com/jhudsl/intro_to_r/blob/5e466776444f0b16e21b07d20cf42b6007977961/modules/Data_Visualization/Data_Visualization.Rmd#L456

Factors

- [x] A lot of nesting happening here.. maybe could break it up? (see below) now this is below
     - https://github.com/jhudsl/intro_to_r/blob/5e466776444f0b16e21b07d20cf42b6007977961/modules/Factors/Factors.Rmd#L97
- [x] take out the `::` - maybe we should try to do this everywhere?
     - https://github.com/jhudsl/intro_to_r/blob/5e466776444f0b16e21b07d20cf42b6007977961/modules/Factors/Factors.Rmd#L181

**Comment by carriewright11** [comment]
Data Viz Lecture

- [ ] slide 25 - typo: The y argument specifies the x axis label.
- [ ] summary slide - need new line for one of the items about `xlim()` and `ylim()
- [ ] `mapping =` is missing in a couple of places... but do we want to remove this everywhere? it was a bit confusing to students... maybe show mapping once? @avahoffman, what do you think?

Data Viz Lab
- [ ] #3 remove ` +` on last line in hints ... although I think I want to change all hints for all labs to be above the chunk the way @avahoffman did in later labs

**Comment by carriewright11** [comment]
> Factors
> 
> * A lot of nesting happening here.. maybe could break it up?
>   
>   * https://github.com/jhudsl/intro_to_r/blob/5e466776444f0b16e21b07d20cf42b6007977961/modules/Factors/Factors.Rmd#L97

@avahoffman, do you mean: https://github.com/jhudsl/intro_to_r/blob/5e466776444f0b16e21b07d20cf42b6007977961/modules/Factors/Factors.Rmd#L101 instead of: https://github.com/jhudsl/intro_to_r/blob/5e466776444f0b16e21b07d20cf42b6007977961/modules/Factors/Factors.Rmd#L97?

**Comment by avahoffman** [comment]
>  mapping = is missing in a couple of places... but do we want to remove this everywhere? it was a bit confusing to students... maybe show mapping once? @avahoffman, what do you think?

Ugh I'm so conflicted about this. It's definitely best programming practices to state the argument but like no one does it, especially w/ ggplot.. what do you think? @carriewright11 

> A lot of nesting happening here.. maybe could break it up? 

Yes did mean the line above :) Not super important.. maybe doing something like 
`data_highschool %>% pull(grade) %>% levels()`
would be more 'tidy' but idk - whatever you think is fine :)

**Comment by carriewright11** [comment]
@padmashris - here are more updates that we wanted to make - we are happy to make these ourselves - so no pressure at all, but if you are interested, feel free to do so!

**Comment by padmashris** [comment]
> 

got it! I might have a little more time after finals end and would be more than happy to look at a few updates!

**Comment by carriewright11** [comment]
OK sounds great! :) Best of luck with your finals!
