### ISSUE TITLE
Update the docker image with these packages

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#213]
- epitools
- faraway
- Others??

**Comment by carriewright11** [comment]
emo

**Comment by carriewright11** [comment]
naniar
patchwork
plotly
DirectLabels ... can't recall if these needed to be added but maybe

**Comment by avahoffman** [comment]
We have naniar but not the others, thanks!

**Comment by avahoffman** [comment]
Looks like I already updated the image! https://hub.docker.com/repository/docker/jhudsl/intro_to_r
