### ISSUE TITLE
Stats notes

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#216]
### Lecture
- [x]  slide 16 has typo: tests test
- [x]   should we introduce that `lm()` exists and describe the difference between `lm()` and `glm()` so people know what it is when they see it? (can still stick with just using `glm()` I think that was great)
- [ ] maybe have factor example with more levels (going to backlog this for now)
- [x]   maybe add these resources: 
- [x]  https://jhudatascience.org/tidyversecourse/model.html#linear-modeling 
- [x]  https://www.scribbr.com/statistics/statistical-tests/  (this is the awesome chart and resource Alex found) 
- [x]  maybe we can add a more indepth stats resource 
    
### Lab
- [x]  question 1 - maybe explain that there will be lots of NA values and why - some countries not studied in the first years of the data collection (some students thought they did something wrong)
- [x]  typo: part 3 label should say part 2

**Comment by avahoffman** [comment]
Thank you!!!

I'm a little conflicted about `lm` vs `glm`. I want to err on the side of fewer functions since stats is already hard for most folks. Maybe just mention that they might see `lm`? @carriewright11
