### ISSUE TITLE
Lab directions 

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#219]
move hints to above chunks for all labs, but also explain that certain sections like `___` or ``????` would need to be replaced when typed in the chunk

**Comment by avahoffman** [comment]
- [ ] Intro
- [ ] RStudio
- [ ] Reproducibility
- [ ] Basic R
- [ ] Data IO
- [ ] Subsetting
- [ ] Summarization
- [ ] Data classes
- [ ] Data cleaning
- [ ] Manipulating
- [ ] Esquisse
- [ ] Data viz
- [ ] factors
- [ ] Statistics
- [ ] Functions
