### ISSUE TITLE
remove `::` from each lecture/lab

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#220]
I think this confused people....and maybe is unnecessarily advanced

**Comment by avahoffman** [comment]
- [ ] Intro
- [ ] RStudio
- [ ] Reproducibility
- [ ] Basic R
- [ ] Data IO
- [ ] Subsetting
- [ ] Summarization
- [ ] Data classes
- [ ] Data cleaning
- [ ] Manipulating
- [ ] Esquisse
- [ ] Data viz
- [ ] factors
- [ ] Statistics
- [ ] Functions
