### ISSUE TITLE
Videos from Summer 2022 on Youtube

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#229]
### Trim recordings from Zoom
- [x]  RStudio + Reproducibility
- [x]  Basic R
- [x]  Data IO
- [x]  Subsetting
- [x]  Summarization
- [x]  Data classes
- [x]  Data cleaning
- [x]  Manipulating
- [x]  Esquisse
- [x]  Data viz
- [x]  Factors
- [x]  Statistics
- [x]  Functions

### Upload to Youtube
- [x]  RStudio + Reproducibility
- [x]  Basic R
- [x]  Data IO
- [x]  Subsetting
- [x]  Summarization
- [x]  Data classes
- [x]  Data cleaning
- [x]  Manipulating
- [x]  Esquisse
- [x]  Data viz
- [x]  Factors
- [x]  Statistics
- [x]  Functions

### Add links to homepage
- [x] Added to RESOURCES tab

**Comment by carriewright11** [comment]
@avahoffman I updated the resource page in PR #235 (I needed to for another issue #221

**Comment by carriewright11** [comment]
Thanks for putting all these on youtube and editing them @avahoffman !

**Comment by avahoffman** [comment]
@carriewright11 Thank you!!
