### ISSUE TITLE
warnings to take care of for actions

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#238]
<img width="930" alt="Screen Shot 2022-12-27 at 10 00 53 AM" src="https://user-images.githubusercontent.com/23014755/209698253-0e2b8038-380f-4e86-a3b9-761af3b9e814.png">

**Comment by carriewright11** [comment]
It's at least working now for PRs so it's getting somewhere :)

**Comment by carriewright11** [comment]
still more changes needed...
<img width="927" alt="Screen Shot 2022-12-27 at 3 20 01 PM" src="https://user-images.githubusercontent.com/23014755/209727485-8f6469ee-276c-480c-aefd-5d174153a0b1.png">

**Comment by carriewright11** [comment]
This is a bit more helpful for that warning:
<img width="912" alt="Screen Shot 2022-12-28 at 11 59 53 AM" src="https://user-images.githubusercontent.com/23014755/209859936-aa279946-3a47-4a11-b486-c8f44c3a7ddb.png">

**Comment by carriewright11** [comment]
<img width="987" alt="Screen Shot 2022-12-28 at 12 33 02 PM" src="https://user-images.githubusercontent.com/23014755/209863311-edcb22d1-9910-4a75-9dd2-0897d4906c8f.png">

**Comment by avahoffman** [comment]
I think this is fixed!
