### ISSUE TITLE
Noticed that main branch keeps rendering

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#239]
not sure why this is....

**Comment by carriewright11** [comment]
could be related to this.. but I'm confused as to why this isn't happening with the PRs:
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

**Comment by carriewright11** [comment]
I think it is triggered by a push and then does a push at the end... but somehow this didn't seem to be a problem before... confusing

**Comment by carriewright11** [comment]
Maybe this will work (https://github.com/orgs/community/discussions/26724):
- name: pull request
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

**Comment by carriewright11** [comment]
This caused an error... still working on it: 

if: github.event_name == 'pull_request' || github.event.pull_request.merged == true

Invalid workflow file: .github/workflows/render-site.yml#L1No steps defined in `steps` and no workflow called in `uses` for the following jobs: run_if
--


[Invalid workflow file: .github/workflows/render-site.yml#L1](https://github.com/jhudsl/intro_to_r/actions/runs/3790174238/workflow)
No steps defined in `steps` and no workflow called in `uses` for the following jobs: run_if

**Comment by carriewright11** [comment]
For now I just got rid of the main branch from the workflow - so that we can manual run for the main branch so that at least for now we don't get tons of redundant large commits to the main branch

**Comment by avahoffman** [comment]
@carriewright11 I think it's because I needed to specify that I only want autodispatch when a Rmd or md is changed. For example, we don't need to rerender if a dataset is modified.
```
on:
  workflow_dispatch:
  push:
    branches: [ main, staging ]
    paths:
      - '**.Rmd'
      - '**.md'
```

**Comment by avahoffman** [comment]
I think this is fixed!

**Comment by carriewright11** [comment]
> I think this is fixed!

YAY:)

**Comment by carriewright11** [comment]
> @carriewright11 I think it's because I needed to specify that I only want autodispatch when a Rmd or md is changed. For example, we don't need to rerender if a dataset is modified.
> 
> ```
> on:
>   workflow_dispatch:
>   push:
>     branches: [ main, staging ]
>     paths:
>       - '**.Rmd'
>       - '**.md'
> ```

sounds great

**Comment by avahoffman** [comment]
🙌🏻 🎉
