### ISSUE TITLE
Automate updates to R version using `config.yml`

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#266]
> Thanks! I think we can make this more extensive and integrated with the individual slides too. Okay merging for now and adding to it later?

sure! just might want an issue to remind ourselves (maybe you already did that though - I am catching up :P) or maybe mine is sufficient

_Originally posted by @carriewright11 in https://github.com/jhudsl/intro_to_r/issues/263#issuecomment-1371349677_

**Comment by avahoffman** [comment]
I think this is done!

**Comment by carriewright11** [comment]
OK cool - I didn't know if you had more extensive plans with the slides - I think it is working well!

**Comment by carriewright11** [comment]
Oh I see - you did this! :) #366 looks nice!!  😊
