### ISSUE TITLE
Day 0 and 1 Notes from winter 2023

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#286]
**INTRO SLIDES**
- [x] Date says 2022 - not 2023
- [x] maybe talk about functions being verbs and objects being nouns
- [x] add data to objects description list
- [x] add biocounductor to the "more on Functions and Packages slide"
- [x]  update that Hadley wickham works at Posit instead of RStudio... mayeb add a slide about the connection between these two
- [x] emphasize pull down menu for cran when installing from menus by adding  a sentence to the image slide
- [x] add slide about how installing only needs to be done once (although I feel like I did do something about that somewhere, but seems like it needs to be emphasized)
- [x] remove installation of jhur from slides

**RESOURCES**
- [x]  Posit is lower case on the resource page 

**RSTUDIO**
- [x] Maybe talk about difference of scripts and Rmarkdown on a slide? Previously I thought ignoring scripts might keep it simple, but maybe we need to describe both (or at least edit all the old images from John to be markdown only)? 
- [x] if we do both maybe just preview what each look like when we first talk about opening the editor
- [x] touch on Posit?

**LAB**
- [x] Maybe we should work through installing the jhur package as part of the lab (like directly include it) and remove it from the intro slides? - in retrospect idk why we didn't do this before :P 
- [x] add coment in the lab about this: “install from sources the package which needs compilation” and I had to type in Yes to get it to run the install...
- [x] I think we should tell them to copy paste one line at a time into the console for the jhur installation step
- [x] Maybe also include discussion about running code in console vs the editor/Rmarkdown

**Installation Gude**
- [x] Maybe add extra info for troubleshooting installation somewhere.  Was R the right version for their operating system?etc. 
- [x] Point them to older versions of RStudio
- [x] Also I think we could make the installation instructions a bit more prominent somewhere on the website? I was struggling to find them :P

**HW1** 
- [x] update about takeaways (called something different I guess)

**Reproducibility**
- [x] some images are kinda small - like the pyramid - could make it bigger
- [x] session info slide was small

**Comment by carriewright11** [comment]
https://community.rstudio.com/t/rstudio-desktop-crashes-on-startup-with-library-not-loaded/130296

**Comment by avahoffman** [comment]
Thanks @carriewright11 🤩

**Comment by carriewright11** [comment]
no problem :)

**Comment by carriewright11** [comment]
https://dailies.rstudio.com/version/2021.09.2+382.pro1/ for older versions of macos @avahoffman  do you recall what Krista had?

**Comment by carriewright11** [comment]
New top of the RStudio lab:
<img width="1054" alt="Screen Shot 2023-01-09 at 5 17 45 PM" src="https://user-images.githubusercontent.com/23014755/211419613-d961001a-c20d-4f58-8ba3-df9efef8119d.png">

**Comment by carriewright11** [comment]
> https://community.rstudio.com/t/rstudio-desktop-crashes-on-startup-with-library-not-loaded/130296

ooh forgot this... maybe I will add to the help page?

**Comment by avahoffman** [comment]
> https://dailies.rstudio.com/version/2021.09.2+382.pro1/ for older versions of macos @avahoffman do you recall what Krista had?

Mac OS 10.14.5

**Comment by carriewright11** [comment]
I think this is done? What do you think @avahoffman ?

**Comment by avahoffman** [comment]
I think so!
