### ISSUE TITLE
directions to change breakout rooms

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#292]
I made a document for this somewhere  - unfortunately I don't know where and it may not have been github

**Comment by carriewright11** [comment]
would be good to add somewhere on the website

**Comment by carriewright11** [comment]
found it! https://docs.google.com/document/d/1YP1pZF1bIm66_Tl15Y3eHl8pGxNIASD33mKCtGCfQzc/edit?usp=sharing

**Comment by carriewright11** [comment]
also this about paths: https://docs.google.com/presentation/d/18u1Vhd3Uq-QprC0btpxS_-Ka-LKVUvncyoqdbGdb-g4/edit#slide=id.g13445a81409_0_54

**Comment by avahoffman** [comment]
awesome! Maybe both of these can go in the drive for the class? Or converted to Rmd eventually :)

**Comment by carriewright11** [comment]
This is done :)
