### ISSUE TITLE
Google for surveys instead of courseplus?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#296]
Kind of want to get rid of courseplus entirely haha. Student found multiple sites/links confusing

**Comment by carriewright11** [comment]
lol I know what you mean - want to do turning in homework somewhere else? or do you think that is still best on courseplus?

**Comment by avahoffman** [comment]
This is done!

**Comment by carriewright11** [comment]
I love when we just have to close one we forgot we already did :P
