### ISSUE TITLE
SUBSETTING: Table of when quotes are required and not

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#304]
`filter()` cannot have quotes but `rename()` can. I'm envisioning a table for this.. will work on it!

| Function 	| no quotes 	| ticks 	| quotation marks 	|
|:---:|:---:|:---:|---|
| `filter()` 	| YES 	| NO 	| NO 	|

**Comment by carriewright11** [comment]
thanks! this has been so tricky haha - cause it is complicated that they work sometimes and not others. The inconsistency of certain things makes people uncomfortable.

**Comment by carriewright11** [comment]
Assigning @avahoffman cause you had  a vision, but I am happy to take a stab at this first if you prefer

**Comment by carriewright11** [comment]
this might help too: https://jhudatascience.org/intro_to_r/quotes_vs_backticks.html
