### ISSUE TITLE
SUBSETTING: Use mutate instead of `rename()`

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#305]
Does it make sense to use `mutate()` to rename columns? Something like

```
df <- mtcars

df %>% mutate(CYL = cyl, .keep = "unused")
# or
df %>% mutate(CYL = cyl) %>% select(-cyl)
```

might be one less function to learn, or we can just mention it but not go into it.

**Comment by carriewright11** [comment]
hmmm interesting, I guess that might make `rename_with` more confusing though without learning `rename`? but mentioning  at least seems worthwhile

**Comment by avahoffman** [comment]
I'm okay not doing this :) Just a thought!
