### ISSUE TITLE
cleaning Notes

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#317]
- [x] remove across from summary
- [x] add replace_na function of tidyr
- [x] change to na_if(Dog, 0) 
- [x] stick to just airqual in slides - **did this as much as it seemed beneficial** - some concepts would be really difficult to show with airquality data or bike or yts - I will keep looking
- [x] ptc_complete with multiple columns?
- [x]  add examples to the backtick quote  resource for case_when and recode
- [x] add a slide about character values vs variable names and why they need quotes
- [x] will add data set to allow people to follow along /combine existing - also to show str_* functions with mutate outside of case_when but I think I will keep simple examples in some cases and just tell them to follow along with the other data 
- [x] check how each slide prints for fit

Lab
- [x] add more hints in general and especially about quotes for values
- [x] people struggled a bit with the "\\." add quotes to the directions and don't use backticks so they don't get confused even though it is a piece of code

**Comment by avahoffman** [comment]
This was great! 

There are a TON of datasets in here and a bunch that are made up. Would be nice if it was one big messy one.

**Comment by carriewright11** [comment]
Yeah I tried to make them simple so people could focus on one thing at a time - I can combine some

**Comment by carriewright11** [comment]
should I drop recode?

**Comment by avahoffman** [comment]
Maybe it could be mentioned without going into detail or practicing it?

**Comment by carriewright11** [comment]
I noticed recode gets used in the stats lecture also - just noting this here

**Comment by carriewright11** [comment]
add str_replace_all?
