### ISSUE TITLE
make a table or resource of when to use what function with a vector or a dataframe 

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#319]
the inconsistency in R makes it really confusing for people
also maybe add to this resource the common error of data %>% pull(variablename) %>% range(variabelname)

**Comment by carriewright11** [comment]
@avahoffman  what do you think about this?

**Comment by avahoffman** [comment]
I think this would be great on the help page! That, and the table of quotations/ticks by function.

**Comment by carriewright11** [comment]
We have these both on the help page:

When should I use quotes (““) or backticks (``)?
Check out our [Guide on when to use quotes or backticks](https://jhudatascience.org/intro_to_r/resources/quotes_vs_backticks.html).

How do I know when to use the pull() function, instead of just using select()?
Check out our [Guide on what functions require pulling values out first](https://jhudatascience.org/intro_to_r/resources/functions_for_vectors.html).

**Comment by carriewright11** [comment]
it's also on our resources page:
