### ISSUE TITLE
factors Notes

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#338]
- maybe describe how to use fct_reorder() without a function too?

**Comment by carriewright11** [comment]
I think we talk about what Clif was saying for numeric values sometimes plotting better as a factor - but maybe not - so could be good to add that! :)

**Comment by avahoffman** [comment]
> * maybe describe how to use fct_reorder() without a function too?

This is actually pretty tricky to do without using base R notation. Might skip this.
