### ISSUE TITLE
survey

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#340]
maybe we can add some stuff about this to the website?

You can do the course evaluation even if you didn't take the course for credit. Use your JHED ID or JHU login and password to log in. If you do not have a JHED ID, sign in as a “Guest User” using the email provided to create your JHU login during course registration. Please contact [JHSPH.courseeval@jhu.edu](mailto:JHSPH.courseeval@jhu.edu) for assistance.

maybe this one:https://courseevaluations.jhsph.edu/Evaluation/Default

**Comment by carriewright11** [comment]
@avahoffman where could we add this? would the syllabus make sense?

**Comment by avahoffman** [comment]
Yeah I think the syllabus makes sense!
