### ISSUE TITLE
`=` on slide 15 of stats lecture

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#341]
Weird, it looks okay here

https://github.com/jhudsl/intro_to_r/blob/809f65d6c49f96e03e929f39501b04c0cd2c3b7b/modules/Statistics/Statistics.Rmd#L166

Make sure this is rendering ok

**Comment by carriewright11** [comment]
need to add summary before lab 1

show na values with t.test

typo about ttest hypothesis for two sample

**Comment by carriewright11** [comment]
get rid of backticks (\`) in the lab and just say the word backticks

**Comment by carriewright11** [comment]
why are the other values different: 
mort <- read_mortality()

mort <- mort %>%
  rename(country = `...1`)
mort_sub <-
  mort %>%
  select(`1980`, `1990`, `2000`, `2010`)

cor(mort_sub)
cor(mort_sub, use = "complete.obs")

**Comment by carriewright11** [comment]
want a different linear spurious correlation example

**Comment by carriewright11** [comment]
this resource actually looks pretty good https://www.statology.org/null-residual-deviance/ - might want to add to resource page but idk

**Comment by carriewright11** [comment]
typo in summary for cor.test making it code

**Comment by carriewright11** [comment]
maybe add interaction `*` to description of regression in R

**Comment by carriewright11** [comment]
the lab question with interaction needs the individual terms too in the key - also someone was confused by the backticks in the description and thought the interaction needed that - adding this to the lecture should fix that hopefully

**Comment by carriewright11** [comment]
and link = logit to lab key and lab

**Comment by carriewright11** [comment]
add that you don't need quotes for variable names and interactions in the quotes vs backticks page

**Comment by clifmckee** [comment]
- [ ] show how to view all intercepts (including comparison group) glm(y ~ x - 1)
