### ISSUE TITLE
STATS: Summary runs over on rendered page / html

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#344]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/15618412/213558549-6c25dd4f-c027-4fad-97d1-82b1a34960b9.png">

**Comment by carriewright11** [comment]
@clifmckee adding you to the issues (based on feedback from each other, ourselves, and students) for the lectures assigned to you - we are totally happy to help you with these but just wanted to give you a heads up so you don't need to look through  our giant list of issues :P
