### ISSUE TITLE
Summarization Notes

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#401]
- [x] should we only show the tidy way for getting the mean etc. with dataframes? (I know we used to show more base R but then kinda seemed to move more away from base R in our materials to make it simpler)
- [x] maybe add more explanation of why you don't need to write the column name in `quantile` if you already pulled it - got a question about that
- [x] for the tb dataset should we show them to change the colnames (the years) so that they are typical instead of dealing with backticks - to show  the  practice of tidy naming? like year_1990 This way we could start moving away from the backtick vs quote conundrum a tad?
- [x] If we remove how to do `rownames_to_column` from the subsetting lecture, then `columns_to_rowname` might be more confusing... showing a tidyverse way to get the means for each country instead might be better?
- [x] got a question before lab about why we need to use summarize when we can just pull the data and apply the math functions. Might be good to add a slide to explain that we be able to do fancier things with summarize later in the module (like `group_by` etc.)
- [x] maybe could be good to also explain in a slide about how summarize creates a new separate tibble (so you don't want to overwrite and reassign your data object) - there was some confusion about that (and that you can name the columns anything you want - and it is the same structure as `rename()` and `mutate()`
- [x] Add a slide to explain (i can't recall if there is one or not) about how to group by two variables and that if you do it sequentially it will overwrite it ... maybe same for count... so count(var1, var2) and groupby(var1, var2) vs count(var1) %>% count(var2) etc.

**after lab1** 
- [x] since we introduce the tidyverse `distinct()` function in an earlier module, maybe we should describe that first and then show `unique()` and how they are different? (do we need to show `unique()`?) People might get confused about how you can't use it in the same way - like: airqual %>% unique(pull(Ozone)) vs. airqual %>% pull(Ozone) %>% unique()
- [ ] slide 40 got some confusion since we didn't save the grouped form of the data... maybe show an example where you save it to something or overwrite it first

**after lab2**
- [x] had some confusion about baseR vs tidy ways of doing things - maybe add a slide explaining that these are base R functions so we will do this in a more base R way

**Lab**
- [x] part 2 tell them to use bike not bike_2 to stay on same page

**Comment by carriewright11** [comment]
Woohoo! Clif did great - these are just comments based on things students asked questions about

**Comment by carriewright11** [comment]
@clifmckee  had the idea of showing how you can add to the summary to show it is a different tibble than the data and that showing proportions can show how things can get weird

**Comment by clifmckee** [comment]
Got partway through this issue, but didn't quite finish with the `distinct()` vs. `unique()` thing and other items. Will try to get through the rest and make sure everything looks okay for next time.
