### ISSUE TITLE
`recode` and `case_when` comparison, use new column name

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#421]
Would be good to show how 

```
data_diet %>% mutate(new_col = recode(Gender, O = "Other"))
```
and
```
data_diet %>% mutate(new_col = case_when(Gender == "Other" ~ "O"))
```

differ.

case_when doesn't assume, and fills in with NAs, while recode is more like "tweaking" a column and populates with the old values.

I think instead of reassigning the `Gender` column, it might be clearer for folks to see if this was `Gender_clean` or something.

**Comment by carriewright11** [comment]
sure sounds good - I can separate this into more slides and make a new variable and also show that you could modify an existing one. I also want to add the true statement to all of them cause it is good practice

**Comment by avahoffman** [comment]
yeah! I think it is nice to show what NOT doing `TRUE ~` does is helpful though.

**Comment by avahoffman** [comment]
I guess there might be some cases where you'd want to fill with NAs?? Maybe? :P
