### ISSUE TITLE
Add this to the FAQ

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#423]
Some people have been getting the following error: Error in exists(cacheKey, where = .rs.WorkingDataEnv, inherits = FALSE) :invalid first argument
Error in assign(cacheKey, frame, .rs.CachedDataEnv) : 
  attempt to use zero-length variable name If you get this you might want to shut down RStudio and open it again. This appears to be a new error in the latest version of RStudio.

**Comment by carriewright11** [comment]
Hopefully Posit fixes this for new versions

**Comment by carriewright11** [comment]
saw this but I haven't tried it : 
As a workaround, I think you can add the following to your ~/.Rprofile:

options(rstudio.help.showDataPreview = FALSE)
and then restart the RStudio session and confirm that getOption("rstudio.help.showDataPreview") reports FALSE.

**Comment by avahoffman** [comment]
I don't think we had this issue this time - closing for now :)
