### ISSUE TITLE
`setdiff()` -- why need to pull if it is a dplyr function ? Is there a base and tidyverse version?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#428]

**Comment by carriewright11** [comment]
Maybe could be nice to show some of these other options: https://dplyr.tidyverse.org/reference/setops.html

**Comment by carriewright11** [comment]
I imagine they are all like that but idk

**Comment by avahoffman** [comment]
Okay, here is some more information on setdiff() .
Example data:
data_As <- tibble(State = c("Alabama", "Alaska"),
                 state_bird = c("wild turkey", "willow ptarmigan"))
data_cold <- tibble(State = c("Maine", "Alaska", "Alaska"),
                    vacc_rate = c(0.795, 0.623, 0.626),
                    month = c("April", "April", "May"))
setdiff() is both a base R and dplyr function. This is confusing and part of the struggle of an open development environment.
When using setdiff() from base R, vectors are required. It shows the elements in the first that are missing from the second:
A_states <- data_As %>% pull(State)
cold_states <- data_cold %>% pull(State)
setdiff(A_states, cold_states)

[1] "Alabama"
When using setdiff() from dplyr, it does something different. It tells us the rows in the first tibble that are not in the second tibble. We have to select “State” column so the columns are identical across the two tibbles.
A_states <- data_As %>% select(State)
cold_states <- data_cold %>% select(State)
setdiff(A_states, cold_states)

# A tibble: 1 × 1
  State  
  <chr>  
1 Alabama
We could also use setdiff() from dplyr  to tell us what rows were removed when filtering a dataframe or tibble:
mt_cars_high_mpg <- mtcars %>% filter(mpg > 20)
setdiff(mtcars, mt_cars_high_mpg)

**Comment by carriewright11** [comment]
I started a PR - feel free to take over if you prefer! otherwise I will just copy over what you have :P
