### ISSUE TITLE
Mention alternative to Esquisse : https://github.com/smouksassi/ggquickeda

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#431]
Do we want to explore this or mention it? It looks more complicated than Esquisse, which might be a bad thing.

https://github.com/smouksassi/ggquickeda

**Comment by carriewright11** [comment]
also this one: autoplot

**Comment by carriewright11** [comment]
or https://alternativeto.net/software/ggraptr/about/
