### ISSUE TITLE
data viz

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#432]
Before Lab1 
- [x]  add a slide before lab one to show that you can modify a plot object by adding to it
- [x]  add links to keys about line types, point types etc. on the theme explanation slides - actually just say that we are going to talk about that soon  because we do it after the lab
- [x] maybe show how you can overwrite your specifications with layers ? idk if this should be before lab one or just in the common error section:
example: 
Orange %>% ggplot(mapping = aes(x = circumference, y = age, color = Tree)) + 
  geom_line(size = 0.8, color = "black", linetype = 2) + 
  geom_point(size = 5, color = "red", alpha = 0.5) + 
  theme_classic()

There are not multiple lines for each tree.
  
  vs. 
Orange %>% ggplot(mapping = aes(x = circumference, y = age, color = Tree)) + 
  geom_line(size = 0.8, color = "black", linetype = 2) + 
  geom_point(size = 5, color = "red", alpha = 0.5) + 
  theme_classic()

- [x] Bonus: is there lol need to remove it I guess
Part 2
- [ ] #523

**Comment by padmashris** [comment]
#500 takes care of 4/5 of these
