### ISSUE TITLE
Rstudio Lecture

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#465]
- [x] Slide 31 mentions adjusting the settings to show code inline. This has changed to Edit > Settings
     - [x] Mention how this is done on a windows machine also (tools > Global Options, I think??)

**Comment by carriewright11** [comment]
this was so tricky... I wonder if we don't want to show them how actually?? 

Also the saturday Sunday lack of filtering step might be to complicated the first time people see code - I might simplify this (cause we teach this later anyway)

**Comment by carriewright11** [comment]
I think there are some redundant slides showing the editor and the console maybe

**Comment by avahoffman** [comment]
> this was so tricky... I wonder if we don't want to show them how actually??

The thing is, they always ask...

**Comment by carriewright11** [comment]
p

> > this was so tricky... I wonder if we don't want to show them how actually??
> 
> The thing is, they always ask...

true... but I wonder if there is a posit page we could point them too? that might be more up-to-date? Also people clearly have different versions, cause different solutions are working for people :P

**Comment by avahoffman** [comment]
Posit's documentation is actually out of date 😂 https://support.posit.co/hc/en-us/articles/200549016-Customizing-the-RStudio-IDE

**Comment by carriewright11** [comment]
haha we can't win!
