### ISSUE TITLE
Subsetting

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#481]
Lecture
- [x] extra package install code was supposed to be hidden
- [x] the first allison pic is wrong :P should be rename not filter
- [x] I could add my tip about it being like assigning an object so new names are on the left for rename (people told me they liked it)
- [ ] maybe do more to lead us into the example in the summarization renaming of the tb dataset
- [x]  remove skim/skimr

Lab
- [ ] lab 1 already had a bonus in it - need to remove that
- [x] remove pipe from key before part3
- [x] wanted to add more hints to lab but forgot that this morning - especially for mutate question but also some of the bonuses: NEWDATA <- OLD_DATA %>% mutate(NEW_COLUMN = OLD_COLUMN)
- [x] remove hint in part two with a pipe
- [x] noticed bonus in key is out-of-date from last edit: **Bonus / Extra practice**: Select the variables that contain the letter "a" from `cars_mt_copy`. needs to be **Bonus / Extra practice**: Select the variables that contain the letter "a" from `cars_mt_copy`. and on the regular one too ugh... 
- [x] also country_pop and other misspellings in some places instead of county_pop
- [x] change the relocate question to not use any renamed columns in case people messed that part up or started again
- [x]  remove distinct() and cover that in summarization as an fyi maybe?

**Comment by avahoffman** [comment]
- [ ] Might want to move the datasets from OCS to jhur or url .. introducing `OCSData` and `here` I think was a lot - unless we plan on using them again. Maybe could mention them at the end?

I know we've gotten feedback before about how there are a lot of datasets, and they wish there were a few we could get really familiar with. Any way we could cut down on them somehow? I think this would probably take some work though.

**Comment by carriewright11** [comment]
lab 1 had bonus already in it :P

**Comment by carriewright11** [comment]
> * [ ]  Might want to move the datasets from OCS to jhur or url .. introducing `OCSData` and `here` I think was a lot - unless we plan on using them again. Maybe could mention them at the end?
> 
> I know we've gotten feedback before about how there are a lot of datasets, and they wish there were a few we could get really familiar with. Any way we could cut down on them somehow? I think this would probably take some work though.

I did this because of an issue about asking for more practice of data import - we will use this for all of subsetting. We can certainly change this however you think is best

**Comment by carriewright11** [comment]
> * [ ]  Might want to move the datasets from OCS to jhur or url .. introducing `OCSData` and `here` I think was a lot - unless we plan on using them again. Maybe could mention them at the end?
> 
> I know we've gotten feedback before about how there are a lot of datasets, and they wish there were a few we could get really familiar with. Any way we could cut down on them somehow? I think this would probably take some work though.

is there a dataset you would like to use? I was also trying to show different public health datasets

**Comment by carriewright11** [comment]
I could add my tip about it being like assigning an object so new names are on the left for rename

**Comment by carriewright11** [comment]
I can maybe switch out the air quality dataset for the bike dataset maybe for cleaning so that it is the same as the reshaping data lecture. - It isn't the best for renaming though sadly. I think I looked into bike already for that but I will look again.
