### ISSUE TITLE
Classes Notes 1/16/24

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#517]
- [x] Got a question about significant figures displayed on the console. Might be worth mentioning on a bonus slide ? Responded with this:

     > Re: significant figures in the console. The short answer, different functions display numeric output differently (even if the real value, stored inside the object, is the same) — you can usually adjust the significant figures via the RStudio options or add on packages. https://tibble.tidyverse.org/articles/numbers.html ... And a short explanation for the display of numerical values for a tibble, numbers without periods are integers without any decimals while numbers with periods at the end just indicate that there is decimal information, it’s just not getting displayed in the print output.

- [x] Sounded like someone was confused what double meant. Not "double decimal" .. 
 
     > Can you specify the number of decimal digits more than double? So say you want 3?  0.xx for instance

**Comment by carriewright11** [comment]
- [ ] maybe show that you need a date version of a variable to then later convert to other options...  for example... go from character to whatever format like ymd and then use year to just get year

**Comment by carriewright11** [comment]
add this to the lab: circ <- read_csv(file = "http://jhudatascience.org/intro_to_r/data/Charm_City_Circulator_Ridership.csv")

**Comment by avahoffman** [comment]
Lab bonus 1: possible solution `circ %>% select(date, date_formatted, everything())` :)

**Comment by carriewright11** [comment]
do we want to keep describing about matrices and lists?? - maybe just lists?

**Comment by carriewright11** [comment]
maybe could remove the slide about testing with `class()` - currently slide 8 seemed a tad redundant
