### ISSUE TITLE
consistently using either "-" or "!" to not select columns or first introduce both

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#519]
I used "-" when not selecting in the subsetting lecture - and noticed I used "!" in cleaning and wrote an issue  to myself to change it to "-"

However, I noticed there is a slide about not selecting columns using "!" in manipulating data (and some lab questions), do we just want to go with one method? or should we introduce both in the subsetting lecture instead?

**Comment by carriewright11** [comment]
This is also in the manipulating data lab

**Comment by carriewright11** [comment]
OK, we discussed that we want to show both ways when we introduce it but then we want to stick with `!` from then on

**Comment by carriewright11** [comment]
so I am going to drop the manipulating data label

**Comment by carriewright11** [comment]
looks like we both did this @avahoffman

**Comment by avahoffman** [comment]
@carriewright11 I didn't do this, I just linked the issue 🙂

**Comment by avahoffman** [comment]
Whoops you're totally right @carriewright11 - I'm so sorry!! I am clearly losing it 😛
