### ISSUE TITLE
Notes on statistics

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#536]
Awesome job @clifmckee !

- [ ] lots of datasets used. I wonder if we could use one, and select columns depending on what we want?
- [ ] The doctors and visits examples.. I wonder if we should use a different example, if the data aren't really normal distributions? Visits - binomial, and hours - gamma?

**Comment by carriewright11** [comment]
this seems like a nice resource: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2938757/
