### ISSUE TITLE
across

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#54]
ideally get to the point of showing across() and  how to write functions maybe if added more days to course

**Comment by avahoffman** [comment]
ava to talk about across, apply and stuff right before functions

theory of loops a lil bit

**Comment by cansavvy** [comment]
Teach about apply maybe: https://github.com/AlexsLemonade/training-modules/blob/master/intro-to-R-tidyverse/03-intro_to_tidyverse.Rmd#L395

**Comment by avahoffman** [comment]
`across()` is now in data summarization. Will try to insert it more into functions as well.

**Comment by carriewright11** [comment]
cool!- I can reinforce this a bit in data cleaning which I think needs an overhaul and should be focused on recoding with case_when()

**Comment by avahoffman** [comment]
because `across()` is now taken care of, I've split this into a new issue: #132
