### ISSUE TITLE
ThemePark added to jhudsl/intro_to_r:1.1

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/intro_to_r#545]
In order for #530 to be addressed, we'll need the `ThemePark` package to be added to this docker image. 

I'll take a look at if this dockerfile is here and I'll file a PR for this.

**Comment by avahoffman** [comment]
Pushing this to https://hub.docker.com/repository/docker/jhudsl/intro_to_r/general v1.1.1

**Comment by avahoffman** [comment]
Resolved by #546
