### ISSUE TITLE
Easier time with `ggplot` using `esquisse` ?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#58]
https://dreamrs.github.io/esquisse/index.html

Cool GUI for ggplot. I think ggplot is really hard for some people. The good thing about this tool is that students who want to dive into the code can still do that (by clicking on the code box at the bottom, or just doing things from scratch) while students with less experience can stick to the GUI and not worry about the code.

**Comment by carriewright11** [comment]
Yeah, I think that's a good idea. Need to figure out how to motivate them to dive into the code maybe. :P

**Comment by avahoffman** [comment]
Maybe we introduce the basics, and then present this as an option for their projects?

**Comment by carriewright11** [comment]
indeed! :)

**Comment by avahoffman** [comment]
- start with this and then discuss limitations
