### ISSUE TITLE
Subsetting tiny fixes

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#587]
- [x] slide 72 say some old stuff about `tb` data which we aren't working with anymore - just needs to be deleted
- [x]  lab part 3 says 1.3 and 1.4 instead of 3.3, 3.4 etc.

**Comment by avahoffman** [comment]
In 3.1, 
```
Create a subset called `county_2012` from `county_pop` that only contains the rows for the year 2012 and only the columns: `county_name`,	`state_name`, `population`. `year` should not be included in `county_sub`.
```
I think this should be `county_2012` not `county_sub`

```
Re-order the rows of `county_2012` by population in increasing order. Use `arrange()`. What is county with the smallest population?
```
Missing a word

**Comment by carriewright11** [comment]
tell them in the slide about errors for filter - remind them how it works- someone got confused - it works on rows based on specified conditions for values across the rows of particular columns

**Comment by carriewright11** [comment]
Check https://github.com/fhdsl/DaSEH/issues/81 for overlap
