### ISSUE TITLE
provide students with more visuals like cheatsheets

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#59]

**Comment by avahoffman** [comment]
Add links to cheatsheets where possible

**Comment by avahoffman** [comment]
put it here : 
![image](https://user-images.githubusercontent.com/15618412/145465633-fa9e43f6-4ce0-4d43-8aa8-a6b5c4f944a3.png)

**Comment by avahoffman** [comment]
Reminder for each lecture!!!
- [ ] @avahoffman 
  - [ ] Data IO
  - [ ] Data Summarization
  - [ ] Manipulating Data
  - [ ] Stats
  - [ ] Iteration Vibes and Functions 
- [ ] @carriewright11 
  - [ ] Intro
  - [ ] RStudio
  - [ ] Subsetting
  - [ ] Factors
  - [ ] Data Cleaning
  - [ ] Data Viz
- [ ] @cansavvy 
  - [ ] Reproducibility 
  - [ ] Basic R
  - [ ] Data classes

**Comment by cansavvy** [comment]
Here's some cheatsheets that may or may not be helpful for this crowd: https://github.com/AlexsLemonade/training-modules/tree/master/module-cheatsheets

**Comment by carriewright11** [comment]
I think this is done... but could make more visuals somehow...
