### ISSUE TITLE
maybe a lecture on factors?

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/intro_to_r#67]
I added an example that I briefly went over last time... but I think we could maybe add this to one of the days. I think it is an important topic. What do you think @avahoffman  and @cansavvy ?

**Comment by avahoffman** [comment]
I agree - super important, could maybe be a "module" of the classes lecture?

**Comment by carriewright11** [comment]
yeah, that's what I was thinking... OK, I'll try to figure out where in the schedule this would make sense

**Comment by cansavvy** [comment]
https://github.com/AlexsLemonade/training-modules/blob/master/intro-to-R-tidyverse/01-intro_to_base_R.Rmd There's stuff about factors in here.

**Comment by cansavvy** [comment]
https://github.com/AlexsLemonade/training-modules/tree/master/intro-to-R-tidyverse

**Comment by carriewright11** [comment]
hmmm I might move this again... I previously showed how helpful forcats is for making plots... but then we would want to do this after the  data visualization module

**Comment by avahoffman** [comment]
@carriewright11 is this resolved?

**Comment by carriewright11** [comment]
Yes, I think so :)
