### ISSUE TITLE
Any particular reason we want to have the schedule like this versus a md table?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#69]
This is pretty hard to read. It also prevents rendering nicely to latex formats. I think John may have done this so the HW keys weren't visible, but I actually don't mind having them accessible.

@cansavvy @carriewright11 do you care if I change this back to md?

https://github.com/jhudsl/intro_to_r/blob/82f75d857a55f3f7ec7d7272469c761ab13ce461/index.Rmd#L140

Looks like md was used previously..
https://github.com/jhudsl/intro_to_r/blob/82f75d857a55f3f7ec7d7272469c761ab13ce461/index.Rmd#L251

**Comment by cansavvy** [comment]
I don't mind. I think md is easier as well.

**Comment by carriewright11** [comment]
yeah that's ok with me

**Comment by carriewright11** [comment]
Perhaps Candace and I got to this after the google sheets idea though - I am ok with the google sheet version or whatever is easiest. I am also OK with md if that is the preference.

**Comment by avahoffman** [comment]
This issue pre-dated the google sheet. Hopefully not too complicated to stick with that!
