### ISSUE TITLE
Add a contributing.md file 

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/intro_to_r#80]
Some file that introduces collaborators to this project would be great. It's a bit confusing about how to add material if you are unfamiliar with the project.

**Comment by cansavvy** [comment]
We need more direct instructions and easier tools to invite collaborations for this repo. We can borrow github actions, tools and their descriptors from https://github.com/jhudsl/OTTR_Template wherever would be helpful.

**Comment by avahoffman** [comment]
I think this is done. I think we can improve it though :)
