### ISSUE TITLE
Be careful about recommending to open things in excel 

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/intro_to_r#82]
If anything I would discourage people to open data in excel because as we know, it thinks everything's a date, so simply by opening a file you might messing up some data. 

May want to tell them about this paper: 
~ 1 in 5 genomics papers has errors thanks to Excel: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1044-7

**Comment by carriewright11** [comment]
maybe you can discuss this in the reproducibility lecture? @cansavvy

**Comment by avahoffman** [comment]
I think we can close this
