### ISSUE TITLE
Make Website button at the end of slides more clear

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/intro_to_r#83]
"Return to syllabus" or something that tells you what that's bringing you to.

**Comment by carriewright11** [comment]
- [ ]  RStudio
- [ ]  Reproducibility
- [ ]  Basic R
- [ ]  Data IO
- [ ]  Subsetting
- [ ]  Summarization
- [ ]  Data classes
- [ ]  Data cleaning
- [ ]  Manipulating
- [ ]  Esquisse
- [ ]  Data viz
- [ ]  factors
- [ ]  Statistics
- [ ]  Functions

**Comment by carriewright11** [comment]
@avahoffman I think it also might help to add the lab directly... like this:
`🏠 [Class Website](https://jhudatascience.org/intro_to_r/)`
`💻 [Lab](https://jhudatascience.org/intro_to_r/modules/Subsetting_Data_in_R/lab/Subsetting_Data_in_R_Lab.Rmd)`

**Comment by avahoffman** [comment]
@carriewright11 this is awesome, good idea!

**Comment by avahoffman** [comment]
This is done!
