### ISSUE TITLE
Make an automatic re-render GHA

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/intro_to_r#84]
I'm lazy and 1) Don't want to re-render everything everytime or have to double check everything.  2) Don't know how to re-render everything. I can set up a GHA and simple docker image to do this for us. Probably not before this year's course though.

**Comment by cansavvy** [comment]
I also am unsure what packages or commands I need to re-render things.

**Comment by carriewright11** [comment]
I like this idea in general. Yes, we can talk about this in a meeting sometime soon

**Comment by avahoffman** [comment]
Agreed this sounds good!

**Comment by avahoffman** [comment]
Woo hoo !!! DONE!
