### ISSUE TITLE
muschellij2/intro_to_r vs jhudsl/intro_to_r

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/intro_to_r#87]
What's the relation of these repositories in practice? It appears this repo is quite a few commits ahead of the original `muschellij2/intro_to_r`. 

Do we want to unlink these? Is `muschellij2/intro_to_r` deprecating?

**Comment by avahoffman** [comment]
I would prefer unlink them, it's an extra step to make sure I don't PR John's repo 😛

**Comment by carriewright11** [comment]
Our content is all originally adapted from John's (hence his repo) who used to teach the course until we did it last time. In fact, he was originally intending to teach last time as well, but his plans changed last minute. We can unlink them so we don't accidentally PR his repo :P indeed I worry about that too. I do think we should have a note somewhere though about it - like in the readme or something.

**Comment by cansavvy** [comment]
We should dettach this from the original `muschellij2/intro_to_r` following this link: https://support.github.com/request/fork?tags=fork

This way `muschellij2/intro_to_r` can be its own thing and we can adapt this how we like without the forking mechanics making things automatically return to `muschellij2/intro_to_r `

**Comment by avahoffman** [comment]
done
