### ISSUE TITLE
Change URL to jhudatascience.org

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/intro_to_r#9]
https://github.com/jhudsl/intro_to_r/blob/9b9f1593318019937e46ce2c103c9b5e64eb597e/Basic_R/index.Rmd#L223
Want it to be easily back compatible if John decides to use our changes

**Comment by carriewright11** [comment]
yup thanks for catching this! I imagine this is probably in many of the lectures/labs..

**Comment by avahoffman** [comment]
@carriewright11 I was thinking a regex, gsub(), or something of that nature, but concerned it might replace something we don't want it to. Think it's best just to do it by hand as we go through the material?

**Comment by carriewright11** [comment]
hmmm good thoughts... yeah, maybe best to search for it as we go through the material.
