### ISSUE TITLE
Broken link to all_the_packages.txt file

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/intro_to_r#90]
https://jhudatascience.org/intro_to_r/all_the_packages.txt

There's an alternative installation method listed but the package list file that is required is not on here that I can see. 

>Alternatively, all the packages used (in any way - homework, lecture, lab), are listed in this text file. If you would like to install all the packages from this file, please download that text file and run this R script.

**Comment by carriewright11** [comment]
thanks for noticing this... I will look into this

**Comment by carriewright11** [comment]
this is obsolete right @avahoffman ?
