### ISSUE TITLE
Package installation steps don't work for me

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/intro_to_r#91]
The instructions for installation packages listed here: https://jhudatascience.org/intro_to_r/#packages

Not sure what the deal is. I can do some more digging but perhaps someone who's more familiar with this repository has a better idea of what's happening: 

<img width="984" alt="Screen Shot 2022-01-03 at 9 24 11 PM" src="https://user-images.githubusercontent.com/23458084/148001396-4737ccdf-bfa4-40b3-a536-f11c7ebb384c.png">

I think in the future a different method for creating a computing environment should be used (either an Rstudio server, docker container, renv, or some combination) but we don't have time right now to implement a new strategy.

**Comment by avahoffman** [comment]
I think this is resolved - perhaps let's make a new issue for our wishlist? Would love to implement docker, GHA build steps (instead of a makefile), etc.

**Comment by avahoffman** [comment]
This has been resolved
